export const errors = {
    en: {
        "requiredId": "vendorId required",
        "requiredTitle": "title required",
        "requiredStore": "storeId required",
        "requireditem": "itemId required",
        "requireActive": "isActive Key required",
        "requireImage": "image_Id required",
        "requiredOffer": "offerId required",
        "requireOrder": "orderId required",
        "requiredsizeId": "Item_sizeId required.",
        "selectStore": "Please firstly select store type",
        "requireBranch": "branch_Id required",
        "alreadyBranch": "This branch already Deleted",
        "invalidOtp": "Invalid Otp Please fill Correct Otp.",
        "invalidAddress": "Not a valid address",
        "invalidAddressProvided": "Invalid address provided.",
        "kycDetailsAlreadySubmitted": "Given KYC details already exist. Please update them",
        "noSuchAccount": "No such account exist with this email.",
        "WrongPassword": "Wrong Password Please fill Correct Password.",
        "WrongOldPassword": "Old Password is wrong  Please fill Correct Password.",
        "deactiveateByAdmin": "This Type Category Items Blocked by Admin",
        "notSamePassword": "Confirm Password should be same as new password",
        "accountAlreadyExist": "Account with given Phone number and Role already exist.",
        "phoneAlreadyExist": "Phone number already exist.",
        "noSuchAccountExist": "No such account exist.",
        "invalidMongoId": "{{key}} must be a valid mongo ID",
        "noDatafound": "No Record Found",
        "modelFound": "With this Name Model already exist",
        "emailAlreadyExist": "Email already Exists",
        "alreadyExist": "Already Exists",
        "categoryExists": "With This Name Category already Exist",
        "menuItemExists": "With This Name Menu Item already Exist",
        "addonsExists": "With This (type and title) Addons already Exist",
        "userExist": "User already Exist",
        "alreadyItemSize": "With This Size Item already Exist",
        "addons_Type": "With This Type title addons_Type  already Exist",
        "invalidAction": "Invalid action",
        "unprocessableEntity": "Unprocessable entity",
        "actionAlreadyTaken": "You have already took action on this order request",
        "invalidQRcode": "Invalid QRcode",
        "somethingwrong": "Something went wrong",
        "invalidOrderInfo": "Invalid Order Info",
        "requestExpired": "Quatation request has been expired! you may contact admin.",
        "accountBlocked": "Account blocked by admin.",
        "sessionExpired": "Session expired! Please login again.",
        "noToken": "Invalid token",
        "unAuthRole": "Unauthorized role! Access denied",
        "accountDelete": "This Account delete by Admin",
        "addressExist": "Address already Exist",
        "orderNotExists": "This type order is not exists",
        "addbyAdmin": "You can't take action on this offer Because this offer add by Admin",
        "phoneNumberNot": "Phone Number not Exists?Please Enter Valid Phone Number",
        "requiredPhoneNo": "Phone Number required",
        "alreadyStore": 'This account have already select store Type',
        "subAdminBlocked": "This Sub Admin Deactivate By Admin",
        "already_used": "This coupon code already used",
        "notAvailable": "This coupon is not available for this restaurant",
        "notAvailable_thisTime": "You can use this coupon from {{Date}}",
        "minimumAmount": "This coupon can't be apply on this order",
        "notParkingAvailable":"No parking available at this time Please wait",
        "alreadyParkingProvide":"Parking number already provided on this order",
        "alreadyTaken":"This Order has been '{{order}}'"
    },
    ar: {
        "requiredId": "vendorId required",
        "requiredTitle": "title required",
        "requiredStore": "storeId required",
        "requireditem": "itemId required",
        "requireActive": "isActice Key required",
        "requireImage": "image_Id required",
        "requiredOffer": "offerId required",
        "requireOrder": "orderId required",
        "requiredsizeId": "Item_sizeId required.",
        "selectStore": "Please firstly select store type",
        "requireBranch": "branch_Id required",
        "alreadyBranch": "This branch already Deleted",
        "invalidOtp": "Invalid Otp Please fill Correct Otp.",
        "invalidAddress": "Not a valid address",
        "invalidAddressProvided": "Invalid address provided.",
        "kycDetailsAlreadySubmitted": "Given KYC details already exist. Please update them",
        "noSuchAccount": "No such account exist with this email.",
        "WrongPassword": "Wrong Password Please fill Correct Password.",
        "WrongOldPassword": "Old Password is wrong  Please fill Correct Password.",
        "deactiveateByAdmin": "This Type Category Items Blocked by Admin",
        "notSamePassword": "Confirm Password should be same as new password",
        "accountAlreadyExist": "Account with given Phone number and Role already exist.",
        "phoneAlreadyExist": "Phone number already exist.",
        "noSuchAccountExist": "No such account exist.",
        "invalidMongoId": "{{key}} must be a valid mongo ID",
        "noDatafound": "No Record Found",
        "modelFound": "With this Name Model already exist",
        "emailAlreadyExist": "Email already Exists",
        "alreadyExist": "Already Exists",
        "categoryExists": "With This Name Category already Exist",
        "menuItemExists": "With This Name Menu Item already Exist",
        "addonsExists": "With This (type and title) Addons already Exist",
        "userExist": "User already Exist",
        "alreadyItemSize": "With This Size Item already Exist",
        "addons_Type": "With This Type title addons_Type  already Exist",
        "requestSentAlready": "For some of the vendors, quotation request already sent.",
        "invalidAction": "Invalid action",
        "unprocessableEntity": "Unprocessable entity",
        // "actionAlreadyTaken": "You have already took action on this quote request",
        "somethingwrong": "Something went wrong",
        "invalidOrderInfo": "Invalid Order Info",
        "bookingStatusError": "Status can't be changed from '{{old}}' state to '{{new}}' state.",
        "requestExpired": "Quatation request has been expired! you may contact admin.",
        "accountBlocked": "Account blocked by admin.",
        "sessionExpired": "Session expired! Please login again.",
        "noToken": "Invalid token",
        "unAuthRole": "Unauthorized role! Access denied",
        "addressExist": "Address already Exist",
        "orderNotExists": "This type order is not exists",
        "actionAlreadyTaken": "You have already took action on this order request",
        "invalidQRcode": "Invalid QRcode",
        "phoneNumberNot": "Phone Number not Exists ? Please Enter Valid Phone Number",
        "requiredPhoneNo": "Phone Number required",
        "alreadyStore": 'This account have already select store Type',
        "subAdminBlocked": "This Sub Admin Deactivate By Admin",
        "already_used": "This coupon code already used",
        "notAvailable": "This coupon is not available for this restaurant",
        "notAvailable_thisTime": "You can use this coupon from {{Date}}",
        "minimumAmount": "This coupon can't be apply on this order",
        "notParkingAvailable":"No parking available at this time Please wait",
        "alreadyParkingProvide":"Parking number already provided on this order",
        "alreadyTaken":"This Order has been '{{order}}'"
    }
};

export const success = {
    en: {
        "addressAdded": "Address added sucessfully",
        "addressUpdated": "Address updated sucessfully",
        "gotLatestAddress": "Got latest address sucessfully",
        "updatePassword": "Update password sucessfully",
        "success": "Success",
        "addTime": "Vendor Opening and Closing time add successfully",
        "editTime": "Vendor Opening and Closing time updated successfully",
        "homeDetailsFetched": "Home details fetch sucessfully",
        "signupSuccessful": "Signup Sucessfully",
        "loginSuccessful": "Login Sucessfully",
        "accountExists": "Account already exist",
        "noSuchAccountExist": "No such account exist",
        "storeAdd": "Store added sucessfully",
        "branchAdd": "Branch added sucessfully",
        "branchEdit": "Branch updated sucessfully",
        "branchstatus": "Branch status update sucessfully",
        "branchDelete": "Branch deleted sucessfully",
        "ItemsAdd": "Menu items added successfully",
        "ItemsUpda": "Menu items updated successfully",
        "profileUpdate": "Profile Updated successfully",
        "gotUserProfile": "Got user profile sucessfully",
        "addCategory": "Category added sucessfully",
        "addShop": "Shop added sucessfully",
        "recordFetched": "Record fetched sucessfully",
        "AddItem_size": "Item Size added sucessfully",
        "updateSuccessful": "Update profile sucessfully",
        "updItemSize": "Item Size updated successfully",
        "addons_type": "Addons Type added successfully",
        "addons_typeEdit": "Addons Type update sucessfully",
        "addonsAdd": "Addons added sucessfully",
        "addonsEdit": "Addons update sucessfully",
        "RecordFound": "Record found",
        "OffersAdd": "Offer added sucessfully",
        "OffersEdit": "Offer updated sucessfully",
        "ImageAdd": "Image added sucessfully",
        "ImageUpdate": "Image updated sucessfully",
        "imageDelete": "Images delete sucessfully",
        "deleteVendor": "Delete vehicle sucessfully",
        "offerDelete": "Offer delete sucessfully",
        "addFaq": "Faq added successfully",
        "editFaq": "Faq updated successfully",
        "doorKeeperSuccessful": "DoorKeeper added sucessfully",
        "updateStatus": "Status updated sucessfully",
        "driverBookingAssigned": "Driver assigned sucessfully",
        "addressRemoved": "Address Removed",
        "driverVerified": "Driver's account verified successfully",
        "issueReported": "issue Reported Successfully",
        "bookingGenerated": "booking Generated Successfully",
        "logOutSuccessful": "User logOut successfully",
        "userComment": "User Comments successfully",
        "orderAdd": "Order Added in cart successfully",
        "orderEdit": "Order updated in cart successfully",
        "orderComplete":"Order completed successfully",
        "qrValidated": "QR code validated Successfully",
        "addBookingDetail": "Booking detail update successfully",
        "menuItemDelete": "Menu Item deleted successfully",
        "itemSizeDelete": "Item Item deleted successfully",
        "addondelete": "Addon  deleted successfully"
    },
    ar: {
        "addressAdded": "Address added sucessfully",
        "addressUpdated": "Address updated sucessfully",
        "gotLatestAddress": "Got latest address sucessfully",
        "updatePassword": "Update password sucessfully",
        "success": "Success",
        "addTime": "Vendor Opening and Closing time add successfully",
        "editTime": "Vendor Opening and Closing time updated successfully",
        "homeDetailsFetched": "Home details fetch sucessfully",
        "signupSuccessful": "Signup Sucessfully",
        "loginSuccessful": "Login Sucessfully",
        "accountExists": "Account already exist",
        "noSuchAccountExist": "No such account exist",
        "storeAdd": "Store added sucessfully",
        "branchAdd": "Branch added sucessfully",
        "branchEdit": "Branch updated sucessfully",
        "branchstatus": "Branch status update sucessfully",
        "branchDelete": "Branch deleted sucessfully",
        "ItemsAdd": "Menu items added successfully",
        "ItemsUpda": "Menu items updated successfully",
        "profileUpdate": "Profile Updated successfully",
        "gotUserProfile": "Got user profile sucessfully",
        "addCategory": "Category added sucessfully",
        "addShop": "Shop added sucessfully",
        "recordFetched": "Record fetched sucessfully",
        "AddItem_size": "Item Size added sucessfully",
        "updateSuccessful": "Update profile sucessfully",
        "updItemSize": "Item Size updated successfully",
        "addons_type": "Addons Type added successfully",
        "addons_typeEdit": "Addons Type update sucessfully",
        "addonsAdd": "Addons added sucessfully",
        "addonsEdit": "Addons update sucessfully",
        "RecordFound": "Record found",
        "OffersAdd": "Offer added sucessfully",
        "OffersEdit": "Offer updated sucessfully",
        "ImageAdd": "Image added sucessfully",
        "ImageUpdate": "Image updated sucessfully",
        "deleteVendor": "Delete vehicle sucessfully",
        "offerDelete": "Offer delete sucessfully",
        "imageDelete": "Image delete sucessfully",
        "addFaq": "Faq added successfully",
        "editFaq": "Faq updated successfully",
        "doorKeeperSuccessful": "DoorKeeper added sucessfully",
        "updateStatus": "Status updated sucessfully",
        "driverBookingAssigned": "Driver assigned sucessfully",
        "addressRemoved": "Address Removed",
        "driverVerified": "Driver's account verified successfully",
        "issueReported": "issue Reported Successfully",
        "bookingGenerated": "booking Generated Successfully",
        "logOutSuccessful": "User logOut successfully",
        "userComment": "User Comments successfully",
        "orderAdd": "Order Added in cart successfully",
        "orderEdit": "Order updated in cart successfully",
        "orderComplete":"Order completed successfully",
        "qrValidated": "QR code validated Successfully",
        "addBookingDetail": "Booking detail update successfully",
        "menuItemDelete": "Menu Item deleted successfully",
        "itemSizeDelete": "Item Item deleted successfully",
        "addondelete": "Addon  deleted successfully"
    }
};


export const fcm = {

    statusUpdate: {
        title: "Update status!",
        body: "Hey {{name}}, your account  '{{status}}' by Admin."
    },
    deleteAccount: {
        title: "Delete Account!",
        body: "Hey {{name}}, your account  '{{status}}' by Admin."
    },
    accept_rejectStatus: {
        title: "Request {{status}}",
        body: "Hey {{name}}, your account request {{status}} by Admin "
    }
};


//git password
//gcEEKZbgAexC2UmcHJqk